#!/bin/sh
set -eu

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PROJECT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
PHP_CLI=${PHP_CLI:-php}

if ! command -v "$PHP_CLI" >/dev/null 2>&1 && [ ! -x "$PHP_CLI" ]; then
    echo "PHP CLI not found or not executable: $PHP_CLI" >&2
    exit 1
fi

"$PHP_CLI" -l "$PROJECT_DIR/src/StripeCheckoutResponseNormalizer.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeVerifiedEventNormalizer.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeCheckoutAttemptRecordPlanner.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeEventReceiptRecordPlanner.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeSandboxCheckoutTransportPlanner.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeSandboxCheckoutTransportResponseGate.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeSandboxCheckoutSealedTransportDouble.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeSandboxCheckoutSealedExecutor.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeBoundedJsonDecoder.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeSandboxCheckoutWireCodec.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeSandboxCheckoutSyntheticByteTransport.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeSandboxCheckoutDecodedTranscriptDouble.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeSandboxCheckoutSyntheticTransportAdapter.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeSandboxCheckoutLoopbackHttpsTransport.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeSandboxCheckoutLoopbackHttpsAdapter.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeSandboxContactReadinessPlanner.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeSandboxContactAuthorizationGate.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeSandboxReadOnlyProbeTransport.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeSandboxReadOnlyProbeOutcomeGate.php"
"$PHP_CLI" -l "$PROJECT_DIR/src/StripeSandboxReadOnlyProbeSyntheticExecutor.php"
"$PHP_CLI" -l "$PROJECT_DIR/package/addon.php"
"$PHP_CLI" -l "$PROJECT_DIR/package/StripeTypedOfflineCheckoutAdapter.php"
"$PHP_CLI" -l "$PROJECT_DIR/package/StripeSandboxReadOnlyProbeTransport.php"
"$PHP_CLI" -l "$PROJECT_DIR/package/StripeSandboxReadOnlyProbeOutcomeGate.php"
"$PHP_CLI" -l "$PROJECT_DIR/package/StripeSandboxReadOnlyProbeSyntheticExecutor.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3c1-foundation-self-test.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3c2-checkout-attempt-storage-self-test.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3c3-event-replay-storage-self-test.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3c4-registration-only-package-self-test.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3d1-install-disabled-rehearsal.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3d2-enable-dry-run-rehearsal.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3d3-atomic-enable-rollback-rehearsal.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3d4-runtime-service-binding-rehearsal.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3d5-synthetic-secret-bootstrap-rehearsal.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3d7-typed-offline-adapter-invocation-rehearsal.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3e1-sandbox-transport-contract-self-test.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3e2-sealed-transport-executor-self-test.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3e3-bounded-wire-codec-self-test.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3e4-synthetic-credential-transport-self-test.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3e5-loopback-https-transport-self-test.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3e5-loopback-https-transport-rehearsal.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/fixtures/p3e5-loopback-https-fixture.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3e6-sandbox-contact-readiness-self-test.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3e8b1-provider-transport-contract-self-test.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3e8b3a-package-adoption-self-test.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3e8b3b-synthetic-operation-self-test.php"
"$PHP_CLI" -l "$PROJECT_DIR/tests/p3e8b3c1-provider-operation-self-test.php"
"$PHP_CLI" "$PROJECT_DIR/tests/p3c1-foundation-self-test.php"
"$PHP_CLI" "$PROJECT_DIR/tests/p3c2-checkout-attempt-storage-self-test.php"
"$PHP_CLI" "$PROJECT_DIR/tests/p3c3-event-replay-storage-self-test.php"
"$PHP_CLI" "$PROJECT_DIR/tests/p3c4-registration-only-package-self-test.php"
"$PHP_CLI" "$PROJECT_DIR/tests/p3e1-sandbox-transport-contract-self-test.php"
"$PHP_CLI" "$PROJECT_DIR/tests/p3e2-sealed-transport-executor-self-test.php"
"$PHP_CLI" "$PROJECT_DIR/tests/p3e3-bounded-wire-codec-self-test.php"
"$PHP_CLI" "$PROJECT_DIR/tests/p3e4-synthetic-credential-transport-self-test.php"
"$PHP_CLI" "$PROJECT_DIR/tests/p3e5-loopback-https-transport-self-test.php"
"$PHP_CLI" "$PROJECT_DIR/tests/p3e6-sandbox-contact-readiness-self-test.php"
"$PHP_CLI" "$PROJECT_DIR/tests/p3e8b1-provider-transport-contract-self-test.php"
"$PHP_CLI" "$PROJECT_DIR/tests/p3e8b3a-package-adoption-self-test.php"
"$PHP_CLI" "$PROJECT_DIR/tests/p3e8b3b-synthetic-operation-self-test.php"
"$PHP_CLI" "$PROJECT_DIR/tests/p3e8b3c1-provider-operation-self-test.php"
